# Generated by Django 5.2.7 on 2025-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cremas',
            fields=[
                ('idcremas', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('tamano', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='desodotrantes',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('tamano', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perfumes',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('tamano', models.IntegerField()),
            ],
        ),
    ]
