# Generated by Django 5.2.7 on 2025-10-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_desodorantes_delete_desodotrantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cremas',
            name='precio_inv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='desodorantes',
            name='precio_inv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='perfumes',
            name='precio_inv',
            field=models.IntegerField(null=True),
        ),
    ]
