# Generated by Django 5.2.1 on 2025-12-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_cremas_imagen_alter_desodorantes_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
