# Generated by Django 5.2.7 on 2025-10-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('inversion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=100)),
                ('invertido', models.IntegerField()),
                ('fechaF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='appadmin.viaje')),
            ],
        ),
    ]
