# Generated by Django 5.2.7 on 2025-10-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cremas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='desodotrantes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='perfumes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
