# Generated by Django 5.2.1 on 2025-10-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_cremas_imagen_desodotrantes_imagen_perfumes_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='desodorantes',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('tamano', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='desodorantes/')),
            ],
        ),
        migrations.DeleteModel(
            name='desodotrantes',
        ),
        migrations.AlterField(
            model_name='cremas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cremas/'),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='perfumes/'),
        ),
    ]
