# Generated by Django 5.2.7 on 2025-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_cremas_precio_inv_desodorantes_precio_inv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cremas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cremas/'),
        ),
        migrations.AlterField(
            model_name='desodorantes',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='desodorantes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='desodorantes/'),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
    ]
